### ISSUE TITLE
Why the fork? What, if anything, is new? 

### ISSUE THREAD

**Issue by danindiana** [pmjdebruijn/Arduino-Entropy-Library#1]
I noticed this is a copy of Walter Anderson's excellent library found https://sites.google.com/site/astudyofentropy/

Why the fork? What is new in this code vs that which can be found via: 

https://sites.google.com/site/astudyofentropy/file-cabinet

**Comment by pmjdebruijn** [comment]
Why do you ask?

The commit log should be an answer to that:
https://github.com/pmjdebruijn/Arduino-Entropy-Library/commits/master

If I recall correctly some of the commits were upstreamed:
https://code.google.com/archive/p/avr-hardware-random-number-generation/source/default/commits
But because the original code wasn't on github (no pull request :(), it's not obvious exactly what.

**Comment by danindiana** [comment]
OH ok. Thanks for the reply. Yes, I am reading the commits/master now. Yes, I see there was much work to be done tidying up.
